const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1100},deviceScaleFactor:1});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:18925/');
await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>i.src).map(i=>i.decode()));});
const initial=await page.evaluate(()=>({figures:document.querySelectorAll('.zoom img').length,loaded:[...document.querySelectorAll('.zoom img')].every(i=>i.complete&&i.naturalWidth>0),overflow:document.documentElement.scrollWidth>innerWidth,captionCount:document.querySelectorAll('.caption').length}));
await page.screenshot({path:path.join(root,'comparison-page.png'),fullPage:true});
await page.locator('#paper-toggle').click();
const widths=await page.locator('.zoom img').evaluateAll(imgs=>imgs.map(i=>i.getBoundingClientRect().width));
await page.locator('#figure-2 .new .zoom').first().click();
const modal=await page.locator('dialog').evaluate(d=>d.open&&d.querySelector('img').naturalWidth>0);
await page.keyboard.press('Escape');
const closed=await page.locator('dialog').evaluate(d=>!d.open);
await page.setViewportSize({width:390,height:844});
const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
const result={...initial,paperWidths:widths,zoomOpened:modal,escapeClosed:closed,mobilePageOverflow:mobileOverflow,errors};
await fs.writeFile(path.join(root,'page-verification.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
await browser.close();
