"""Render the closed GUI component study without modifying experiment evidence."""
from pathlib import Path
import csv
import hashlib
import json
import math

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "analysis/pace_live_20260923"
PAPER = ROOT / "paper"
summary_path = DATA / "joint_v3_closeout.json"
summary = json.loads(summary_path.read_text())
source_summary = Path(summary["source_summary"])
local_source_summary = DATA / "joint_v3_summary.json"
if source_summary.is_absolute():
    valid_source = source_summary.parts[-3:] == ("analysis", "pace_live_20260923", "joint_v3_summary.json")
else:
    valid_source = (ROOT / source_summary).resolve() == local_source_summary.resolve()
if not valid_source:
    raise ValueError("Closeout references a different source summary")
integrity = json.loads((DATA / "live_release_integrity.json").read_text())
if integrity.get("schema") != "pace-live-release-integrity/1" or integrity.get("summary_excluded_fields") != [
    "input_dir", "prior_run.input_dir"
]:
    raise ValueError("Unexpected live release integrity rules")
if integrity["summary_original_raw_sha256"] != summary["source_summary_sha256"]:
    raise ValueError('Release program list disagrees with the original summary hash')
source_bytes = local_source_summary.read_bytes()
source_data = json.loads(source_bytes)
if not isinstance(source_data.get("input_dir"), str) or not isinstance(source_data.get("prior_run"), dict) or not isinstance(
    source_data["prior_run"].get("input_dir"), str
):
    raise ValueError("Summary path metadata is missing or malformed")
del source_data["input_dir"]
del source_data["prior_run"]["input_dir"]
canonical = json.dumps(source_data, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
if hashlib.sha256(canonical).hexdigest() != integrity["summary_canonical_sha256"]:
    raise ValueError("Scientific or billing fields differ from the frozen summary")
for name, expected_key in (("joint_v3_pairs.csv", "pairs_csv_sha256"), ("joint_v3_tight.csv", "tight_csv_sha256")):
    if hashlib.sha256((DATA / name).read_bytes()).hexdigest() != integrity[expected_key]:
        raise ValueError(f"{name} differs from the frozen table input")
pairs = list(csv.DictReader((DATA / "joint_v3_pairs.csv").open()))
tight = list(csv.DictReader((DATA / "joint_v3_tight.csv").open()))
assert len(pairs) == 12 and len(tight) == 4
assert all(row["initial_states_match"] == "True" for row in pairs)
for policy, prefix in [("agent", "agent"), ("program_fallback", "pace")]:
    means = [sum(int(row[f"{prefix}_bill_{bound}_nusd"]) for row in pairs) / len(pairs)
             for bound in ("lower", "upper")]
    assert all(math.isclose(a, b, rel_tol=1e-12)
               for a, b in zip(means, summary["all_pair_mean_bill_bounds_nusd"][policy]))


def milli(value):
    return f"{float(value) / 1_000_000:.3f}"


def bounds(lower, upper):
    if lower == upper:
        return milli(lower)
    return f"[{milli(lower)}, {milli(upper)}]"


def table(label, caption, headers, rows, spacing="3pt"):
    return "\n".join([
        "% Generated by rewrite-review/render_live_tables.py from closed experiment records.",
        r"\begin{table}[htbp]", r"\centering", r"\caption{" + caption + "}",
        r"\label{" + label + "}", r"\tablefont",
        r"\setlength{\tabcolsep}{" + spacing + "}",
        r"\begin{tabular}{@{}" + "l" + "r" * (len(headers) - 1) + "@{}}",
        r"\toprule", " & ".join(r"\multicolumn{1}{c}{" + h + "}" for h in headers) + r" \\",
        r"\midrule", *[" & ".join(row) + r" \\" for row in rows],
        r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])


main_rows = []
for label, key, success_key, stop_key in [
    ("Agent", "agent", "agent_successes", "agent_billing_stops"),
    ("Program + fallback", "program_fallback", "pace_successes", "pace_billing_stops"),
]:
    lo, hi = summary["all_pair_mean_bill_bounds_nusd"][key]
    main_rows.append([label, f"{summary[success_key]}/12", str(summary[stop_key]), bounds(lo, hi)])
main = table("tab:live-main",
    "Observed outcomes and serving costs for twelve paired Calendar tasks.\nMean cost bounds are in milli-USD and include extraction and any fallback.\nTheir endpoints combine known charges with the saved reservations for unconfirmed costs; they are not confidence intervals.\nInterrupted runs remain unsuccessful outcomes, and the agent has one additional step-limit failure.\nServing costs exclude the compilation of the fixed program and the separate compilation attempt.",
    ["Serving path", "Success (of 12)", "Interrupted (count)", r"\shortstack{Mean cost bounds\\(milli-USD)}"], main_rows, "4pt")

outcomes = {"billing_stop": "Interrupted", "step_cap": "Step limit", "done": "Success",
            "program_return": "Success", "prefix_denied": "Denied"}
conditions = {"clean": "Clean", "renamed_submit": "Renamed submit", "blocking_dialog": "Blocking dialog"}
detail_rows = []
for row in pairs:
    detail_rows.append([row["seed"], conditions[row["arm"]], outcomes[row["agent_termination"]],
                       outcomes[row["pace_termination"]],
                       bounds(int(row["agent_bill_lower_nusd"]), int(row["agent_bill_upper_nusd"])),
                       bounds(int(row["pace_bill_lower_nusd"]), int(row["pace_bill_upper_nusd"])),
                       (row["fields_correct_at_fallback"] + "/6") if row["fields_correct_at_fallback"] else "--"])
details = table("tab:live-pairs",
    'All paired tasks specified in advance, including provider interruptions and unsuccessful execution.\nCosts use milli-USD.\nBracketed values give lower and upper accounting bounds, and costs shown without brackets are confirmed.\nP+F means program execution followed by agent fallback on an execution error.\nFields counts the six target values already correct when fallback begins.\nAll pairs start from matching application and interface states.',
    ["Seed", "Condition", "Agent", "P+F", r"\shortstack{Agent cost\\(milli-USD)}", r"\shortstack{P+F cost\\(milli-USD)}", "Fields (of 6)"], detail_rows, "2pt")
tight_rows = []
for index, row in enumerate(tight, 1):
    tight_rows.append([str(index), conditions[row["arm"]], outcomes[row["termination"]],
                       bounds(int(row["bill_lower_nusd"]), int(row["bill_upper_nusd"])),
                       milli(row["prefix_ceiling_nusd"]), milli(row["prefix_occupied_nusd"])])
details += "\n" + table("tab:live-tight",
    "Four tight-budget tests in their arrival order set in advance.\nCosts and prefix totals use milli-USD.\nThe reference increases by 20 milli-USD per scheduled arrival, including a denied arrival.\nThe prefix total includes charges and saved reservations for unsettled calls.\nThe first task is denied before any model call or GUI service, so this test does not satisfy the theorem's assumption that default service costs at most its reference charge.",
    ["Arrival", "Condition", "Outcome", r"\shortstack{Cost\\(milli-USD)}", r"\shortstack{Prefix ceiling\\(milli-USD)}", r"\shortstack{Prefix total\\(milli-USD)}"], tight_rows, "3pt")

outputs = {"live_results_table.tex": main, "live_details_tables.tex": details}
for name, content in outputs.items():
    assert content.count(r"\begin{table}") == content.count(r"\tablefont")
    (PAPER / name).write_text(content)
verification = {
    "source_sha256": {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                      for p in [summary_path, DATA / "joint_v3_pairs.csv", DATA / "joint_v3_tight.csv"]},
    "output_sha256": {name: hashlib.sha256(content.encode()).hexdigest() for name, content in outputs.items()},
    "paired_bill_means_verified": 4,
    "paired_states_verified": 12,
    "cost_unit": "milli-USD",
    "interval_kind": 'Unknown bills bounded by known charges and saved reservations, not confidence intervals',
}
verification_path = ROOT / "analysis/pace_closeout_20260923/live-table-verification.json"
verification_path.parent.mkdir(parents=True, exist_ok=True)
verification_path.write_text(json.dumps(verification, indent=2) + "\n")
print("Rendered three live-study tables; verified twelve pairs and four bill-bound means.")
